language: python
cache: pip
jobs:
  include:
    - stage: test
      python: "3.8"
    - stage: test
      python: "3.9"

install:
  # TODO run these in parallel
  # API container deps
  - pip install -r src/Codenalysis/api/requirements.txt

  # Web container deps
  - npm install --save-dev --prefix $(pwd)/src/Codenalysis/web/

script:
  - flake8 src/Codenalysis/api
  - eslint src/Codenalysis/web
