version: "3.3"
volumes:
  # ignore all css from the docker container and do not mount to my local dir
  # This is because the CSS files shouldn't be modified. Only the sass files
  # So no need to store them locally.
  compiled_css:
services:
  nginx:
    depends_on:
      - web
    restart: always
    build:
      context: ./src/Codenalysis/nginx
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "service", "nginx", "status", "|", "grep", "\\[ ok \\] nginx is running"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  db:
    restart: always
    build:
      context: src/Codenalysis/db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  web:
    restart: always
    depends_on:
      - api
      - auth
    build:
      context: src/Codenalysis/web/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
      HOST: 0.0.0.0
      PORT: '3000'
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "start.js"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/Codenalysis/web/src:/codenalysis/src
      - ./src/Codenalysis/web/public:/codenalysis/public
      - compiled_css:/codenalysis/src/assets/css
  api: 
    depends_on:
      - db
      - auth
    restart: always
    build:
      context: src/Codenalysis/api
      dockerfile: ops/Dockerfile
    environment:
      FLASK_ENV: development
    env_file:
      - secrets.env
    healthcheck:
      test: ["CMD", "!", "curl", "http://localhost/api/v1/healthcheck", "|", "grep", "NOT OK"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/Codenalysis/api:/codenalysis
    tty: true
    stdin_open: true
  auth: 
    depends_on:
      - redis
      - db
    restart: always
    build:
      context: src/Codenalysis/auth
      dockerfile: ops/Dockerfile
    environment:
      FLASK_ENV: development
    env_file:
      - secrets.env
    healthcheck:
      test: ["CMD", "curl", "http://localhost/api/v1/auth/healthcheck", "|", "grep", "OK"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/Codenalysis/auth:/auth
    tty: true
    stdin_open: true
  redis: 
    restart: always
    image: redis:6.2.1
    # build:
    #   context: src/Codenalysis/api
    #   dockerfile: opts/Dockerfile
